ListaLibrosMVC/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ListaLibrosMVC.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }

        public DbSet<Libro> Libros { get; set; }
    }
}

ListaLibrosMVC/Models/ErrorViewModel.cs
using System;

namespace ListaLibrosMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ListaLibrosMVC/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ListaLibrosMVC.Models
{
    public class Libro
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Nombre { get; set; }

        public string Autor { get; set; }

        public string ISBN { get; set; }
    }
}

ListaLibrosMVC/Controllers/HomeController.cs
using ListaLibrosMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ListaLibrosMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ListaLibrosMVC/Controllers/LibrosController.cs
using ListaLibrosMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ListaLibrosMVC.Controllers
{
    public class LibrosController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public Libro Libro { get; set; }
        
        public LibrosController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Libro = new Libro();
            if(id == null) // si no hay id
            {
                return View(Libro); // se crea uno nuevo
            }
            Libro = _db.Libros.FirstOrDefault(u=>u.Id==id); // si no se edita el que tenga el id devuelto
            if(Libro == null)
            {
                return NotFound();
            }
            return View(Libro);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert()
        {
            if (ModelState.IsValid)
            {
                if(Libro.Id == 0)
                {
                    _db.Libros.Add(Libro);
                }
                else
                {
                    _db.Libros.Update(Libro);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Libro);
        }

        #region APICalls
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Libros.ToListAsync() }); // recupera el libro y lo pasa cada vez que se llame esta API
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var libroBD = await _db.Libros.FirstOrDefaultAsync(u => u.Id == id);
            if (libroBD == null)
            {
                return Json(new { success = false, message = "Error al eliminar." });
            }
            _db.Libros.Remove(libroBD);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Eliminado." });
        }
        #endregion
    }
}

ListaLibrosMVC/Views/Home/Index.cshtml
<div class="text-center">
    <h1 id="indexTitulo" class="display-4">Bienvenido</h1>    
</div>
<br />
<div>
    <p>
        A continuación se muestran imágenes informativas con edición a base de CSS:
    </p>
</div>
<div id="contenido" class="row">
    <div id="left" class="col-4">
        <article id="gatoart">
            <img src="~/img/gato.png" id="gatoIMG"/>
            <div id="gatodatos">
                <h3 id="gatotitulo">Gatos</h3>
                <p id="gatodescripcion">
                    No cabe duda que los gatos son una excelente compañía. Son perfectos cómplices para las personas que buscan un compañero con quien descansar, que le guste pasar momentos tranquilos y sobretodo aquel que busca un amigo fiel. Muchos artistas afirman que son la mejor compañía y, a veces, una gran inspiración.
                </p>
            </div>
        </article>       
    </div>
    <div id="center" class="col-4">
        <article id="perroart">
            @*<img src="~/img/perro.jpg" id="perroIMG" />*@
            <div id="perrodatos">
                <h3 id="perrotitulo">Perros</h3>
                <p id="perrodescripcion">
                    Ya desde la prehistoria se han documentado casos de asociación entre estos mamíferos descendientes del lobo y el ser humano. Cuando el hombre se dio cuenta de que podía ser un compañero de caza muy eficaz se creó una relación que ha evolucionado hasta la actualidad.
                </p>
            </div>
        </article>
    </div>
    <div id="right" class="col-4">
        <article id="snakeart">
            <div id="snakedatos">
                <h3 id="snaketitulo">Serpientes</h3>
                <span id="snakesubtitulo">Atheris Chlorechis</span>
                <p id="snakedescripcion">
                    Es una especie de víbora venenosa que se encuentra solo en los bosques de África occidental. Actualmente no se reconocen subespecies.
                </p>
            </div>
        </article>
    </div>
</div>

ListaLibrosMVC/Views/Libros/Index.cshtml
<br />
<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Lista de Libros</h2>
    </div>
    <div class="col-3 offset-3">
        <a asp-action="Upsert" asp-controller="Libros" class="btn btn-info form-control text-white">Agregar nuevo libro</a>
    </div>
    <div class="col-12 border p-3">
        <table id="CargarDT" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Autor</th>
                    <th>ISBN</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/ListaLibros.js"></script>
}

ListaLibrosMVC/Views/Libros/Upsert.cshtml
@model ListaLibrosMVC.Models.Libro

<br />
<h2 class="text-info">@(Model.Id!=0 ? "Editar información" : "Crear libro")</h2>
<br />
<div class="border container" style="padding:30px">
    <form method="post">
        @if(Model.Id != 0) { 
            <input type="hidden" asp-for="Id"/>
        }
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <div class="form-group row">
        <div class="col-4">
            <label asp-for="Nombre"></label>
        </div>
        <div class="col-6">
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger col-2"></span>
        </div>
        <div class="col-4">
            <label asp-for="Autor"></label>
        </div>
        <div class="col-6">
            <input asp-for="Autor" class="form-control" />
            <span asp-validation-for="Autor" class="text-danger col-2"></span>
        </div>
        <div class="col-4">
            <label asp-for="ISBN"></label>
        </div>
        <div class="col-6">
            <input asp-for="ISBN" class="form-control" />
            <span asp-validation-for="ISBN" class="text-danger col-2"></span>
        </div>
        <div class="col-3 offset-4">
            <button type="submit" class="btn btn-primary form-control">@(Model.Id!=0 ? "Modificar" : "Crear")</button>
        </div>
        <div class="col-3">
            <a asp-action="Index" class="btn btn-success form-control">Volver a la lista</a>
        </div>
    </div>
    </form>
</div>

@section Scripts{ 
    <partial name="_ValidationScriptsPartial" />
}

ListaLibrosMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lista de libros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link type="text/css" rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div id="cont" class="container">
                <a id="logo" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a id="links" class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a id="links" class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a id="links" class="nav-link" asp-area="" asp-controller="Libros" asp-action="Index">Lista de libros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; <script>document.write(new Date().getFullYear())</script> ListaLibrosMVC - Desarrollado por: Bryan Méndez Garita
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>